<?xml version="1.0" encoding="utf-8"?><Database Name="QLTTN" Class="QLTTNDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-U3DA8K5\KOICHEN;Initial Catalog=QLTTN;Integrated Security=True" SettingsObjectName="ThiTracNghiem.Properties.Settings" SettingsPropertyName="QLTTNConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CapDo" Member="CapDos">
    <Type Name="CapDo">
      <Column Name="maCD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCD" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="CapDo_CauHoi" Member="CauHois" ThisKey="maCD" OtherKey="maCD" Type="CauHoi" />
    </Type>
  </Table>
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="maCH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="maCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maMH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Association Name="CauHoi_CT_DeThi" Member="CT_DeThis" ThisKey="maCH" OtherKey="maCH" Type="CT_DeThi" />
      <Association Name="CauHoi_DapAn" Member="DapAns" ThisKey="maCH" OtherKey="maCH" Type="DapAn" />
      <Association Name="CapDo_CauHoi" Member="CapDo" ThisKey="maCD" OtherKey="maCD" Type="CapDo" IsForeignKey="true" />
      <Association Name="KhoiLop_CauHoi" Member="KhoiLop" ThisKey="maKhoi" OtherKey="maKhoi" Type="KhoiLop" IsForeignKey="true" />
      <Association Name="MonHoc_CauHoi" Member="MonHoc" ThisKey="maMH" OtherKey="maMH" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_DeThi" Member="CT_DeThis">
    <Type Name="CT_DeThi">
      <Column Name="maDT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maCH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CauHoi_CT_DeThi" Member="CauHoi" ThisKey="maCH" OtherKey="maCH" Type="CauHoi" IsForeignKey="true" />
      <Association Name="DeThi_CT_DeThi" Member="DeThi" ThisKey="maDT" OtherKey="maDT" Type="DeThi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_GiangDay" Member="CT_GiangDays">
    <Type Name="CT_GiangDay">
      <Column Name="maGV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLop" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GiaoVien_CT_GiangDay" Member="GiaoVien" ThisKey="maGV" OtherKey="maGV" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="LopHoc_CT_GiangDay" Member="LopHoc" ThisKey="maKhoi,maLop" OtherKey="maKhoi,maLop" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DapAn" Member="DapAns">
    <Type Name="DapAn">
      <Column Name="maCH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DungSai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="CauHoi_DapAn" Member="CauHoi" ThisKey="maCH" OtherKey="maCH" Type="CauHoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeThi" Member="DeThis">
    <Type Name="DeThi">
      <Column Name="maDT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maMH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="maGV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TenDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ThoiGianLamBai" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DeThi_CT_DeThi" Member="CT_DeThis" ThisKey="maDT" OtherKey="maDT" Type="CT_DeThi" />
      <Association Name="DeThi_Thi" Member="This" ThisKey="maDT" OtherKey="maDT" Type="Thi" />
      <Association Name="GiaoVien_DeThi" Member="GiaoVien" ThisKey="maGV" OtherKey="maGV" Type="GiaoVien" IsForeignKey="true" />
      <Association Name="KhoiLop_DeThi" Member="KhoiLop" ThisKey="maKhoi" OtherKey="maKhoi" Type="KhoiLop" IsForeignKey="true" />
      <Association Name="MonHoc_DeThi" Member="MonHoc" ThisKey="maMH" OtherKey="maMH" Type="MonHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoVien" Member="GiaoViens">
    <Type Name="GiaoVien">
      <Column Name="maGV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maMH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="GiaoVien_CT_GiangDay" Member="CT_GiangDays" ThisKey="maGV" OtherKey="maGV" Type="CT_GiangDay" />
      <Association Name="GiaoVien_DeThi" Member="DeThis" ThisKey="maGV" OtherKey="maGV" Type="DeThi" />
      <Association Name="GiaoVien_KyThi" Member="KyThis" ThisKey="maGV" OtherKey="maGV" Type="KyThi" />
      <Association Name="MonHoc_GiaoVien" Member="MonHoc" ThisKey="maMH" OtherKey="maMH" Type="MonHoc" IsForeignKey="true" />
      <Association Name="NguoiDung_GiaoVien" Member="NguoiDung" ThisKey="maGV" OtherKey="maND" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocSinh" Member="HocSinhs">
    <Type Name="HocSinh">
      <Column Name="maHS" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="maLop" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Association Name="HocSinh_Thi" Member="This" ThisKey="maHS" OtherKey="maHS" Type="Thi" />
      <Association Name="LopHoc_HocSinh" Member="LopHoc" ThisKey="maKhoi,maLop" OtherKey="maKhoi,maLop" Type="LopHoc" IsForeignKey="true" />
      <Association Name="NguoiDung_HocSinh" Member="NguoiDung" ThisKey="maHS" OtherKey="maND" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoiLop" Member="KhoiLops">
    <Type Name="KhoiLop">
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="KhoiLop_CauHoi" Member="CauHois" ThisKey="maKhoi" OtherKey="maKhoi" Type="CauHoi" />
      <Association Name="KhoiLop_DeThi" Member="DeThis" ThisKey="maKhoi" OtherKey="maKhoi" Type="DeThi" />
      <Association Name="KhoiLop_LopHoc" Member="LopHocs" ThisKey="maKhoi" OtherKey="maKhoi" Type="LopHoc" />
    </Type>
  </Table>
  <Table Name="dbo.KyThi" Member="KyThis">
    <Type Name="KyThi">
      <Column Name="maKT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayThi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoaiKT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="maGV" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DaThi" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="KyThi_Thi" Member="This" ThisKey="maKT" OtherKey="maKT" Type="Thi" />
      <Association Name="GiaoVien_KyThi" Member="GiaoVien" ThisKey="maGV" OtherKey="maGV" Type="GiaoVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiNguoiDung" Member="LoaiNguoiDungs">
    <Type Name="LoaiNguoiDung">
      <Column Name="maLND" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLND" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LoaiNguoiDung_NguoiDung" Member="NguoiDungs" ThisKey="maLND" OtherKey="maLND" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="maKhoi" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLop" Type="System.String" DbType="VarChar(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="LopHoc_CT_GiangDay" Member="CT_GiangDays" ThisKey="maKhoi,maLop" OtherKey="maKhoi,maLop" Type="CT_GiangDay" />
      <Association Name="LopHoc_HocSinh" Member="HocSinhs" ThisKey="maKhoi,maLop" OtherKey="maKhoi,maLop" Type="HocSinh" />
      <Association Name="KhoiLop_LopHoc" Member="KhoiLop" ThisKey="maKhoi" OtherKey="maKhoi" Type="KhoiLop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="maMH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenMH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="MonHoc_CauHoi" Member="CauHois" ThisKey="maMH" OtherKey="maMH" Type="CauHoi" />
      <Association Name="MonHoc_DeThi" Member="DeThis" ThisKey="maMH" OtherKey="maMH" Type="DeThi" />
      <Association Name="MonHoc_GiaoVien" Member="GiaoViens" ThisKey="maMH" OtherKey="maMH" Type="GiaoVien" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="maND" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="maLND" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NguoiDung_GiaoVien" Member="GiaoVien" ThisKey="maND" OtherKey="maGV" Type="GiaoVien" Cardinality="One" />
      <Association Name="NguoiDung_HocSinh" Member="HocSinh" ThisKey="maND" OtherKey="maHS" Type="HocSinh" Cardinality="One" />
      <Association Name="LoaiNguoiDung_NguoiDung" Member="LoaiNguoiDung" ThisKey="maLND" OtherKey="maLND" Type="LoaiNguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Thi" Member="This">
    <Type Name="Thi">
      <Column Name="maHS" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maKT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Diem" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="DeThi_Thi" Member="DeThi" ThisKey="maDT" OtherKey="maDT" Type="DeThi" IsForeignKey="true" />
      <Association Name="HocSinh_Thi" Member="HocSinh" ThisKey="maHS" OtherKey="maHS" Type="HocSinh" IsForeignKey="true" />
      <Association Name="KyThi_Thi" Member="KyThi" ThisKey="maKT" OtherKey="maKT" Type="KyThi" IsForeignKey="true" />
    </Type>
  </Table>
</Database>